#! /usr/bin/env python
# encoding: utf-8

bld(
    features='cxx cxxshlib pyext',
    source=bld.path.ant_glob('**/*.cpp'),
    target='fifi',
    name='fifi-python',
    use=['STEINWURF_VERSION', 'pybind11_includes', 'fifi']
)
